# Generated by Django 4.1.2 on 2022-12-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_alter_product_options_alter_product_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
