# Generated by Django 4.1.2 on 2022-12-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукт'},
        ),
    ]
